import TanStackProvider from '@/components/TanStackProvider/TanStackProvider';
import AuthProvider from '@/components/AuthProvider/AuthProvider';
import '@/styles/globals.css';

import type { Metadata } from 'next';
import { Lato, Comfortaa } from 'next/font/google';
import PageLoader from '@/components/PageLoader/PageLoader';
import ThemeBodyWrapper from '@/components/ThemeBodyWrapper/ThemeBodyWrapper';
import { Toast } from '@/components/ui/Toast/Toast';

const lato = Lato({
  subsets: ['latin'],
  variable: '--font-family',
  weight: ['400', '700'],
  display: 'swap',
});

const comfortaa = Comfortaa({
  subsets: ['latin'],
  variable: '--second-family',
  weight: ['700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Лелека - онлайн записник',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="uk" className={`${lato.variable} ${comfortaa.variable}`}>
      <ThemeBodyWrapper>
        <TanStackProvider>
          <AuthProvider>
            <Toast />
            <PageLoader>{children}</PageLoader>
          </AuthProvider>
        </TanStackProvider>
      </ThemeBodyWrapper>
    </html>
  );
}
